//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juegos
    {
        public int IdJuego { get; set; }
        public string Titulo { get; set; }
        public string Foto { get; set; }
        public string Argumento { get; set; }
        public Nullable<int> Precio { get; set; }
    }
}
