//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPedidos
    {
        public int IdPedido { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdJuego { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
